[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

["art:fourteen"]
source = "github"
github = "PixelOS-AOSP/art"
branch = "fourteen"

["bionic:fourteen"]
source = "github"
github = "PixelOS-AOSP/bionic"
branch = "fourteen"

["bootable_recovery:fourteen"]
source = "github"
github = "PixelOS-AOSP/bootable_recovery"
branch = "fourteen"

["build:fourteen"]
source = "github"
github = "PixelOS-AOSP/build"
branch = "fourteen"

["build_soong:fourteen"]
source = "github"
github = "PixelOS-AOSP/build_soong"
branch = "fourteen"

["device_lineage_sepolicy:fourteen"]
source = "github"
github = "PixelOS-AOSP/device_lineage_sepolicy"
branch = "fourteen"

["external_arm-optimized-routines:fourteen"]
source = "github"
github = "PixelOS-AOSP/external_arm-optimized-routines"
branch = "fourteen"

["external_jemalloc_new:fourteen"]
source = "github"
github = "PixelOS-AOSP/external_jemalloc_new"
branch = "fourteen"

["external_skia:fourteen"]
source = "github"
github = "PixelOS-AOSP/external_skia"
branch = "fourteen"

["frameworks_av:fourteen"]
source = "github"
github = "PixelOS-AOSP/frameworks_av"
branch = "fourteen"

["frameworks_native:fourteen"]
source = "github"
github = "PixelOS-AOSP/frameworks_native"
branch = "fourteen"

["frameworks_opt_telephony:fourteen"]
source = "github"
github = "PixelOS-AOSP/frameworks_opt_telephony"
branch = "fourteen"

["hardware_google_pixel-sepolicy:fourteen"]
source = "github"
github = "PixelOS-AOSP/hardware_google_pixel-sepolicy"
branch = "fourteen"

["packages_apps_ParanoidSense:fourteen"]
source = "github"
github = "PixelOS-AOSP/packages_apps_ParanoidSense"
branch = "fourteen"

["packages_apps_Settings:fourteen"]
source = "github"
github = "PixelOS-AOSP/packages_apps_Settings"
branch = "fourteen"

["packages_apps_TouchGestures:fourteen"]
source = "github"
github = "PixelOS-AOSP/packages_apps_TouchGestures"
branch = "fourteen"

["packages_apps_Updates:fourteen"]
source = "github"
github = "PixelOS-AOSP/packages_apps_Updates"
branch = "fourteen"

["packages_modules_Connectivity:fourteen"]
source = "github"
github = "PixelOS-AOSP/packages_modules_Connectivity"
branch = "fourteen"

["packages_services_Telecomm:fourteen"]
source = "github"
github = "PixelOS-AOSP/packages_services_Telecomm"
branch = "fourteen"

["system_core:fourteen"]
source = "github"
github = "PixelOS-AOSP/system_core"
branch = "fourteen"

["system_sepolicy:fourteen"]
source = "github"
github = "PixelOS-AOSP/system_sepolicy"
branch = "fourteen"

["system_update_engine:fourteen"]
source = "github"
github = "PixelOS-AOSP/system_update_engine"
branch = "fourteen"

["vendor_aosp:fourteen"]
source = "github"
github = "PixelOS-AOSP/vendor_aosp"
branch = "fourteen"

["vendor_custom-preference:fourteen"]
source = "github"
github = "PixelOS-AOSP/vendor_custom-preference"
branch = "fourteen"
