[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

["android_device_oneplus_dodge:lineage-23.2"]
source = "github"
github = "LineageOS/android_device_oneplus_dodge"
branch = "lineage-23.2"

["android_device_oneplus_sm8750-common:lineage-23.2"]
source = "github"
github = "LineageOS/android_device_oneplus_sm8750-common"
branch = "lineage-23.2"

["android_hardware_oplus:lineage-23.2"]
source = "github"
github = "LineageOS/android_hardware_oplus"
branch = "lineage-23.2"

["android_kernel_oneplus_sm8750-devicetrees:lineage-23.2"]
source = "github"
github = "LineageOS/android_kernel_oneplus_sm8750-devicetrees"
branch = "lineage-23.2"

["android_kernel_oneplus_sm8750-modules:lineage-23.2"]
source = "github"
github = "LineageOS/android_kernel_oneplus_sm8750-modules"
branch = "lineage-23.2"

["android_kernel_oneplus_sm8750:lineage-23.2"]
source = "github"
github = "LineageOS/android_kernel_oneplus_sm8750"
branch = "lineage-23.2"
